### ISSUE TITLE
Shard cannot be stopped

### ISSUE THREAD

**Issue by Zero3** [Francessco121/Discore#82]
It seems like it is not possible to stop a Shard. This waits forever:

````
Shard.StopAsync();
Shard.WaitUntilStoppedAsync().Wait();
````

Maybe I am doing something wrong. Is there another way one is supposed to gracefully shut things down?

**Comment by Francessco121** [comment]
`StopAsync` sets a `ManualResetEvent` when it's done (successfully) that `WaitUntilStoppedAsync` waits on. Since you're not awaiting `StopAsync`, you might be missing an exception thrown from it that's preventing it from completing.

You may also be deadlocking the underlying socket if you're calling `StopAsync` from the same thread as a Gateway event for example.

I recommend passing a `CancellationToken`. If I remember correctly, when the token expires inside `StopAsync` it will force the socket to close anyway.

**Comment by Zero3** [comment]
Hi @Francessco121 :)

Interesting. Thanks for getting back to me. I was not aware that `StopAsync()` could fail like that. So I tried this instead:

````
Shard.StopAsync().Wait();
````

but that leads to this exception:

````
Unhandled exception. System.AggregateException: One or more errors occurred. (The CancellationTokenSource has been disposed.)
 ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at Discore.WebSocket.Internal.GatewaySocket.DisconnectAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at Discore.WebSocket.Internal.Gateway.FullDisconnect()
   at Discore.WebSocket.Shard.StopAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
````

I will try experimenting with a `CancellationToken` instead, as you suggest, and see if I have more luck with that.

**Comment by Zero3** [comment]
I tried this, but it also blocks on the final `.Wait()` forever:

````
CancellationTokenSource cancelSource = new();
Shard.StartAsync(cancelSource.Token).Wait();
cancelSource.Cancel();
Shard.WaitUntilStoppedAsync().Wait();
````

I also tried this, but it leads to the same exception shown above:

````
CancellationTokenSource cancelSource = new();
Shard.StartAsync(cancelSource.Token).Wait();
cancelSource.Cancel();
Shard.StopAsync().Wait();
````

And just in case, I also tried this, which also leads to the same exception:

````
CancellationTokenSource cancelSource = new();
Shard.StartAsync(cancelSource.Token).Wait();
cancelSource.Cancel();
Shard.WaitUntilStoppedAsync(cancelSource.Token).Wait();
````

Could you clarify *any* good way of shutting down Discore? :)

**Comment by Francessco121** [comment]
So, looking into this further it seems like this is a bug. I actually get the same exception. I haven't seen this before because my personal bot never actually calls stop since it's always running.

> Could you clarify any good way of shutting down Discore? :)

It really is just as simple as calling `StopAsync`, and then if you're completely done, calling `Dispose`. That is, if stop worked :)

**Comment by Francessco121** [comment]
Ok, this issue *should* be all fixed now. Please try out the new version 4.4.1!

**Comment by Zero3** [comment]
@Francessco121 seems to work now :). Thanks.
